id: I1B978080
ocr_import_info:
  timestamp: '2023-06-28T07:18:14.258018+00:00'
  batch_id: batch-afa5
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 07:26:58.250807+00:00
last_modified: 2023-06-28 07:26:58.250812+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12658
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12658
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྩ་བ།
  languages:
  - bo
  author: དཔལ་རབ་པོ་ཞི་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9718088478882557
  ocr_word_median_confidence_index: 0.99989812
bases:
  I1KG12681:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12681
      total_pages: 595
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12681.txt
    statistics:
      ocr_word_median_confidence_index: 0.99989812
      ocr_word_mean_confidence_index: 0.9718088478882557
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
